; Script generated by Inno Setup
; Fully standalone installer without PowerShell/Batch script dependency

#define MyAppName "w7repair"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "MX4938avbe"
#define MyAppExeName "w7repair.exe"

[Setup]
PrivilegesRequired=admin
AppId={{433C160B-01EA-4C4D-9710-7122181D546C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=no
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=w7repair_install
SetupIconFile=#103.ico
SolidCompression=yes
WizardStyle=classic dynamic
DisableWelcomePage=no
DisableFinishedPage=no
WizardImageFile=titra.bmp
WizardSmallImageFile=1000-7.png

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"; LicenseFile: "license_en.txt"
Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"; LicenseFile: "license_zh_tw.txt"

[Files]
Source: "C:\Users\user\source\repos\WindowsProject1\x64\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "winre.jpg"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "shutdown.exe"; \
  Parameters: "/r /o /t 1"; \
  Description: "{cm:RunDescription}"; \
  Flags: postinstall unchecked

[UninstallRun]
Filename: "dism.exe"; Parameters: "/Unmount-Image /MountDir:""{app}\mount"" /Discard"; Flags: runhidden


[UninstallDelete]
Type: filesandordirs; Name: "{app}\mount"
Type: files; Name: "{app}\winre.wim"
Type: files; Name: "{app}\winre.wim.bak"


// Stop WinRE >> Copy new winre to app >> mount >> copy app >> rewrite winpeshl >> change wallpaper >> save changes >> replace old winre.wim with new one
[Code]
function ProcessAndInstallWinRE(): Boolean;
var
  ResultCode: Integer;
  RecoveryDir, OrigWimPath, WorkWimPath, BackupWimPath, MountDir, Sys32Dir: String;
  IniPath, WallpaperPath, IniContent: String;
begin
  Result := False;
  
  RecoveryDir := ExpandConstant('{win}\System32\Recovery');
  OrigWimPath := RecoveryDir + '\winre.wim';
  WorkWimPath := ExpandConstant('{app}\winre.wim');
  BackupWimPath := ExpandConstant('{app}\winre.wim.bak');
  MountDir := ExpandConstant('{app}\mount');
  Sys32Dir := MountDir + '\Windows\System32';
  IniPath := Sys32Dir + '\winpeshl.ini';
  WallpaperPath := Sys32Dir + '\winre.jpg';

  Exec('reagentc.exe', '/disable', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  if not FileExists(OrigWimPath) then
  begin
    MsgBox(FmtMessage(CustomMessage('ErrNotFoundWinRE'), [RecoveryDir]), mbError, MB_OK);
    Exit;
  end;

  if not FileExists(BackupWimPath) then
  begin
    CopyFile(OrigWimPath, BackupWimPath, False);
  end;

  if not CopyFile(OrigWimPath, WorkWimPath, False) then
  begin
    MsgBox(CustomMessage('ErrCopyWinRE'), mbError, MB_OK);
    Exit;
  end;

  ForceDirectories(MountDir);
  Exec('dism.exe', Format('/Mount-Image /ImageFile:"%s" /Index:1 /MountDir:"%s"', [WorkWimPath, MountDir]), '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  if ResultCode <> 0 then
  begin
    MsgBox(CustomMessage('ErrMountWinRE'), mbError, MB_OK);
    Exit;
  end;

  CopyFile(ExpandConstant('{app}\w7repair.exe'), Sys32Dir + '\w7repair.exe', False);

  IniContent := '[LaunchApp]' + #13#10 + 'AppPath = %SystemDrive%\Windows\System32\w7repair.exe';
  SaveStringToFile(IniPath, IniContent, False);

  if FileExists(ExpandConstant('{app}\winre.jpg')) then
  begin
    Exec('takeown.exe', Format('/f "%s"', [WallpaperPath]), '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec('icacls.exe', Format('"%s" /grant administrators:F', [WallpaperPath]), '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    CopyFile(ExpandConstant('{app}\winre.jpg'), WallpaperPath, False);
  end;

  Exec('dism.exe', Format('/Unmount-Image /MountDir:"%s" /Commit', [MountDir]), '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  if FileExists(OrigWimPath) then
  begin
    DeleteFile(OrigWimPath);
  end;

  CopyFile(WorkWimPath, OrigWimPath, False);
  Exec('reagentc.exe', '/enable', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

  Result := True;
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    WizardForm.StatusLabel.Caption := CustomMessage('StatusConfiguring');
    WizardForm.ProgressGauge.Style := npbstMarquee;

    ProcessAndInstallWinRE();

    WizardForm.ProgressGauge.Style := npbstNormal;
    WizardForm.ProgressGauge.Position := WizardForm.ProgressGauge.Max;
  end;
end;

// Uninstall
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
  RecoveryDir, OrigWimPath, BackupWimPath, MountDir: String;
begin

  if CurUninstallStep = usUninstall then
  begin
    RecoveryDir := ExpandConstant('{win}\System32\Recovery');
    OrigWimPath := RecoveryDir + '\winre.wim';
    BackupWimPath := ExpandConstant('{app}\winre.wim.bak');
    MountDir := ExpandConstant('{app}\mount');


    Exec('dism.exe', Format('/Unmount-Image /MountDir:"%s" /Discard', [MountDir]), '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

    Exec('reagentc.exe', '/disable', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);

    if FileExists(BackupWimPath) then
    begin
      if FileExists(OrigWimPath) then
      begin
        DeleteFile(OrigWimPath);
      end;
      CopyFile(BackupWimPath, OrigWimPath, False);
    end;
    
    Exec('reagentc.exe', '/enable', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

[Messages]
english.WelcomeLabel1=Revert the Recovery Console into Classical Appearance
english.WelcomeLabel2=This wizard will restore the recovery console into Windows Vista/7-like appearance. %n%nPlease note that your default settings of recovery partition will be modified. You may need an external recovery drive to repair computer if installation is not successful.

chinesetraditional.WelcomeLabel1=將修復主控台還原為經典外觀
chinesetraditional.WelcomeLabel2=此安裝程式將把修復主控台還原為類似 Windows Vista/7 的外觀。%n%n請注意，您的復原磁碟區預設設定將被修改。如果安裝不成功，您可能需要外部安裝光碟來修復電腦。

[CustomMessages]
english.RunDescription=Reboot to Windows RE immediately
chinesetraditional.RunDescription=立即重新啟動至 Windows RE

english.StatusConfiguring=Configuring Windows RE...... Please wait.
chinesetraditional.StatusConfiguring=正在設定 Windows RE，請稍候......

english.ErrNotFoundWinRE=Cannot find winre.wim in %1, please check your WinRE status with reagentc /info.
chinesetraditional.ErrNotFoundWinRE=在 %1 找不到 winre.wim，請使用 reagentc /info 檢查 WinRE 狀態。

english.ErrCopyWinRE=Failed to copy WinRE.
chinesetraditional.ErrCopyWinRE=複製 WinRE 失敗。

english.ErrMountWinRE=Cannot mount WinRE.
chinesetraditional.ErrMountWinRE=無法掛載 WinRE。